//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temporada()
        {
            this.Reservas = new HashSet<Reserva>();
        }

        // string nom, decimal multiplicador, int dataIniciDay, int dataIniciMonth, int dataFinalDay, int dataFinalMonth
        public Temporada(string nom, decimal multiplicador, int dataIniciDay, int dataIniciMonth, int dataFinalDay, int dataFinalMonth)
        {
            Nom = nom;
            Multiplicador = multiplicador;
            DataIniciDay = dataIniciDay;
            DataIniciMonth = dataIniciMonth;
            DataFinalDay = dataFinalDay;
            DataFinalMonth = dataFinalMonth;

            this.Reservas = new HashSet<Reserva>();
        }

        public int IDTemporada { get; set; }
        public string Nom { get; set; }
        public decimal Multiplicador { get; set; }
        public int DataIniciDay { get; set; }
        public int DataIniciMonth { get; set; }
        public int DataFinalDay { get; set; }
        public int DataFinalMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
