//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada
    {
        private string nomTemporada;
        private int day1;
        private int month1;
        private int day2;
        private int month2;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temporada()
        {
            this.Reservas = new HashSet<Reserva>();
        }

        public Temporada(string nomTemporada, decimal multiplicador, int day1, int month1, int day2, int month2)
        {
            this.nomTemporada = nomTemporada;
            Multiplicador = multiplicador;
            this.day1 = day1;
            this.month1 = month1;
            this.day2 = day2;
            this.month2 = month2;
        }

        public int IDTemporada { get; set; }
        public string Nom { get; set; }
        public decimal Multiplicador { get; set; }
        public int DataIniciDay { get; set; }
        public int DataIniciMonth { get; set; }
        public int DataFinalDay { get; set; }
        public int DataFinalMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
