//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dual_Hotel_EX3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipusHabitacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipusHabitacio()
        {
            this.Habitacios = new HashSet<Habitacio>();
            this.Reserva_Has_Tipus_Habitacio = new HashSet<Reserva_Has_Tipus_Habitacio>();
        }

        public TipusHabitacio(int capacitat, string descripcio, decimal? suplementPersona, string nom)
        {
            Capacitat = capacitat;
            Descripcio = descripcio;
            SuplementPersona = suplementPersona;
            Nom = nom;
        }

        public int IDTipus { get; set; }
        public int Capacitat { get; set; }
        public string Descripcio { get; set; }
        public Nullable<decimal> SuplementPersona { get; set; }
        public string Nom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacio> Habitacios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva_Has_Tipus_Habitacio> Reserva_Has_Tipus_Habitacio { get; set; }
    }
}
